services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: .
    init: true
    ports:
      - 4200:4200
      - 5000:5000
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

